### ISSUE TITLE
Problems about installing lua-opencv

### ISSUE THREAD

**Issue by Iamlwq** [art-programmer/FloorplanTransformation#1]
First of all, very amazing work. And I am trying to test on my own test images.

I installed torch and most of the torch packages successfully. But I found the link of lua--opencv and lunatic-python is out-of-date. I tried to complie the source code, but I failed. I want to know which version of lua are you using? And how did you install lua--opencv, by using luarocks or source code? And which source code did you use specificly?

Here is some code I found:
https://github.com/satoren/luaOpenCV
https://github.com/VisionLabs/torch-opencv
https://github.com/bastibe/lunatic-python
https://github.com/OddSource/lunatic-python

**Comment by Iamlwq** [comment]
Solved!

**Comment by art-programmer** [comment]
Glad that you are interested in this work and you solved the issue. Just for references, I used Lua5.1 and https://github.com/VisionLabs/torch-opencv.

**Comment by tansangxtt** [comment]
@Iamlwq Hi, could you list all of the dependencies you installed.  Actually, I tried and failed
