### ISSUE TITLE
Using your dataset

### ISSUE THREAD

**Issue by Docopoper** [art-programmer/FloorplanTransformation#19]
Do you mind if I use the vector outputs of your system as a dataset for my own paper? Naturally I will reference yours.

Also regarding that, what is the scale of the numbers indicating the positions of the wall endpoints?

I want to use these buildings to simulate WiFi signals, so it would be useful to know the pixel scale in meters if you have that.

**Comment by chenliu-wustl** [comment]
Please feel free to use the outputs. However, we don't have scale information. We only have distributed raster images without any scale information.

**Comment by Docopoper** [comment]
Cool, thank you. In that case I'll just give them reasonable random sizes.

**Comment by Docopoper** [comment]
Actually I just realised that I can probably infer scale from the width of the doors.

This website seems to give specs on that:
http://web.mit.edu/cron/group/chinahousing/english/resources/BuildingCode.html
