### ISSUE TITLE
Disable Gurobi?

### ISSUE THREAD

**Issue by happyfrank** [art-programmer/FloorplanTransformation#2]
Hello @art-programmer Thank for you share this amazing code.
I wanna ask if it's possiable to disable Gurobi module? Cause I don't have Gurobi License.
Will it increase the computation time?

**Comment by chenliu-wustl** [comment]
Sorry for the late response. The Integer Programming requires Gurobi. To disable the integer programming part (and use heuristics to connect corners), you can add argument _withoutQP=true_ when calling the function _invertFloorplan_. But the final results will be worse without Integer Programming.

**Comment by art-programmer** [comment]
We now provide a solver without Gurobi at *pytorch/IP.py*.
