### ISSUE TITLE
Licence for this project

### ISSUE THREAD

**Issue by inuex3** [art-programmer/FloorplanTransformation#25]
Hello. 

I'm an engineer and now making an application using machine vision.
I was looking for how to recognize floor plan images and finally found out this project for my work and I'm really interested in using it.
But my question is what open source license does this project have?
Could I use this source code in our Product or only for academic use?

Thanks in advance.

**Comment by tnzk** [comment]
Just in case you are not aware of, this repo has [LICENSE](https://github.com/art-programmer/FloorplanTransformation/blob/master/LICENSE) file. I have no relation with the authors so just FYI.

**Comment by inuex3** [comment]
I missed this file.
Thank you for your cooperation!
