### ISSUE TITLE
error loading module 'checkpoints' from file 

### ISSUE THREAD

**Issue by KenWang94** [art-programmer/FloorplanTransformation#3]
![2018-03-10 11-20-10](https://user-images.githubusercontent.com/34003317/37237868-179e44f2-2455-11e8-8b73-e60b7523cf54.png)

**Comment by chenliu-wustl** [comment]
Indeed an "end" is missing to close the if statement. Thank you for letting us know!

It seems that you might also need to specify the full path (YOUR_PATH/*.t7) to the pose estimation model. Thank you for your interest in our work!
