### ISSUE TITLE
Provided pre-trained model for Pytorch does not perform good.

### ISSUE THREAD

**Issue by fasihgul** [art-programmer/FloorplanTransformation#30]
As the pytorch pre-trained model gives alot of prediction errors as compared to lua implementation. Can you please provide evaluated checkpoint for pytorch implementation. and also single image prediction function .

**Comment by andrew-begain** [comment]
@fasihgul hi,do you sucess run the pytorch version? can you load the pretrain model drn_d_54-0e0534ff.pth? can you send me if you sucess load the model ? thanks

**Comment by fasihgul** [comment]
I was able to run lua version successfuly.
