### ISSUE TITLE
Don'tHavePermissionToAccessUrl

### ISSUE THREAD

**Issue by bangbv** [art-programmer/FloorplanTransformation#33]
Hi Chen Liu,

I tried to run the model but I have got the error message as below. I don't have permission to access this URL. Could you help me?

![image](https://user-images.githubusercontent.com/11347880/83477574-c6d76300-a4bd-11ea-8920-549ff886712d.png)

**Comment by andrew-begain** [comment]
@bangbv hi,have you solve this problems?could you tell me how to solve it? thanks

**Comment by bangbv** [comment]
Hi Andrew, you will find out the models from this link (http://dl.yf.io/drn/). You can download the models to your pc and change the path in the source code to point to the new directory.

**Comment by andrew-begain** [comment]
@bangbv thank you very much!

**Comment by bangbv** [comment]
done
