### ISSUE TITLE
torch/install/bin/luajit: main.lua:63: bad argument #2 to 'max' (number expected, got nil)

### ISSUE THREAD

**Issue by KenWang94** [art-programmer/FloorplanTransformation#4]
![2018-03-16 21-03-15](https://user-images.githubusercontent.com/34003317/37522182-23c26034-295e-11e8-9438-3380b674f642.png)
![2018-03-16 21-03-56](https://user-images.githubusercontent.com/34003317/37522186-28a4ce0c-295e-11e8-9ecf-8e9ee5c02808.png)

**Comment by art-programmer** [comment]
Sorry for the late response. It's a bug. I just fixed it. Thank you very much for reporting it.
