### ISSUE TITLE
Issue with lua cv  lua/5.1/cv/init.lua:339: attempt to call field 'initAllocatorCUDA' (a nil value)

### ISSUE THREAD

**Issue by venkat9yash** [art-programmer/FloorplanTransformation#7]
Hi,

I have installed cv library using luarocks install cv but even after the installation when I kick off the training process, I get the following error. I was wondering if you can point in the direction if I am installing something wrong. 
![screenshot from 2018-04-07 16-21-14](https://user-images.githubusercontent.com/3903556/38460010-be3d46a6-3a7f-11e8-8041-5e1f544d2695.png)

**Comment by art-programmer** [comment]
I noticed that you feed the "" to the argument -loadPoseEstimationModel. It should be the path to the downloaded pose estimation model. However, the error itself might be something related to OpenCV, which is not trivial to compile correctly. I am planning to re-implement the code in PyTorch (maybe in June or earlier) to avoid these compilation issues.
